spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    username: root # 数据库用户名
    password: 123456 # 数据库密码
    url: jdbc:mysql://127.0.0.1:3306/healthy?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8 # 数据库链接
  jackson:
    default-property-inclusion: non_null # JSON输出不能空
  redis:
    host: 127.0.0.1 # Redis域名
    port: 6379 # Redis端口
    password: 123456 # Redis密码
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件最大大小
      max-request-size: 50MB # 请求的总最大大小
  resources:
    static-locations: file:img/,classpath:/static/ # 静态资源路径
  freemarker:
    suffix: .html # freemarker后缀名
server:
  port: 8080 # tomcat服务器端口
#  servlet:
#    context-path: /healthy # 项目环境上下文变量
logging:
  level:
    com.cdutcm.healthy.dataobject.mapper: debug # 显示SQL语句
    com.baomidou.mybatisplus.extension.service: debug # 显示SQL语句
    io.swagger.models.parameters.AbstractSerializableParameter: error # Swagger2
healthy:
  wechat:
    mpAppId: wx2ceb95a69575f2cb # 微信Appid
    mpAppSecret: 5f427b2b78004bc66112e37e7a956aab # 微信Secret
    token: wechatSignature # 微信token
    templateId:
      bodyIndex: bwLTu_E-lETORwitseLwC56P14Vj3X5jBO-OyR5309I #微信模板消息ID
  url:
    wechatMpAuthorize:  # 微信授权地址 个人信息不便展示
    returnUrl:  # 登录跳转首页
    #returnUrl: # 登录跳转首页
    perfectUrl:  # 完善用户信息页面地址
    adminLogin:  # 管理员登录地址
    healthy: # 项目地址
    domain: #
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml